### ISSUE TITLE
Database type incorrect.

### ISSUE THREAD

**Issue by EvanCarroll** [davgra04/findlocalshows-perl#3]
https://github.com/davgra04/findlocalshows-perl/blob/master/flsp-db/sql/schema.sql#L22

artists.id is of type `int`. However the foreign key on the table `events` is of type `TEXT`. They should be the same type.

**Comment by EvanCarroll** [comment]
I'm going to close this issue out because see you have an `id` and a `bit_id`. I didn't realize they were two different things. But I would consider linking through to id instead of using `bit_id` for the link.

**Comment by davgra04** [comment]
Thanks, that sounds good. The id vs bit_id distinction doesn't make a ton of sense in retrospect. I think I was originally protecting against the possibility of the BandsInTown supplied ID not always being unique, which 1) is unlikely and 2) is ineffective because I am still enforcing a UNIQUE constraint on bit_id. I think I may simplify this by using the BandsInTown supplied id only, and dropping the bit_id column.
